# Generated by Django 4.1.6 on 2023-11-27 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=100)),
                ('qoute_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('active', models.BooleanField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='feedback_jobs',
            name='freelancer',
        ),
        migrations.RemoveField(
            model_name='feedback_jobs',
            name='jobs',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='freelancer',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='skills',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='Feedback_jobs',
        ),
        migrations.DeleteModel(
            name='Freelancer',
        ),
        migrations.DeleteModel(
            name='Jobs',
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.poll'),
        ),
    ]
